const ALL_QUESTIONS = [
  // ── Purpose & Contribution (30) ──────────────────────────────────────────
  "What do you feel most called to create or contribute to the world?",
  "If your life had a title, what would it be — and why?",
  "What problem in the world breaks your heart enough to want to fix it?",
  "What would you build, create, or leave behind if you knew it would last forever?",
  "What does the world need that only you can offer in your unique way?",
  "If you could dedicate the next decade to one cause, what would it be?",
  "What contribution would make you feel your time on earth was well spent?",
  "What do you create that makes others feel less alone?",
  "If your work could change one thing about humanity, what would it be?",
  "What gift have you been given that you feel obligated to share?",
  "What would you do with your life if you already had everything you needed?",
  "What is the one thing you would regret not having tried?",
  "Where does your deepest passion meet the world's deepest need?",
  "What would you fight for even if no one paid you and no one praised you?",
  "What kind of world do you want to help build, even in a small way?",
  "If you could mentor one generation of people, what would you teach them?",
  "What do you believe in so deeply you would stake your reputation on it?",
  "What movement or idea do you wish existed that you could help create?",
  "What would you do if you knew the whole world was watching and rooting for you?",
  "What is the most generous version of your potential?",
  "What would you dedicate yourself to if recognition were never part of the equation?",
  "If your purpose were a single verb — not a title — what would it be?",
  "What void in the world aches at you every time you notice it?",
  "What skill or knowledge do you have that could genuinely change someone's life?",
  "What would you create if resources, time, and talent were unlimited?",
  "What does service look like in your most authentic expression?",
  "If you could speak to a million people, what is the one thing you would say?",
  "What injustice makes you angry enough to act?",
  "What is the most meaningful thing you have ever done for another person?",
  "If your life were a gift to the world, what would the card say?",

  // ── Fear & Freedom (30) ──────────────────────────────────────────────────
  "What would you pursue if fear, money, and time were no obstacle?",
  "What dream have you been quietly carrying but been too afraid to speak aloud?",
  "What would you do differently if you knew you could not fail?",
  "What version of yourself are you holding back, and what is stopping them?",
  "If you woke up tomorrow with nothing to lose, what would you do first?",
  "What desire keeps returning no matter how many times you silence it?",
  "What would the most courageous version of you do right now?",
  "What are you pretending not to want because wanting it feels too risky?",
  "If shame and judgment were removed from the equation, who would you become?",
  "What would you attempt if the only person watching was your future self?",
  "What are you waiting for permission to begin?",
  "What fear has been masquerading as wisdom or practicality?",
  "What would you do if you were ten times bolder than you are today?",
  "What chapter of your life are you afraid to write because of how it might end?",
  "What would freedom feel like in your body — and what is standing between you and it?",
  "What have you talked yourself out of that still calls to you?",
  "What risk is your soul asking you to take that your mind keeps vetoing?",
  "If your fear had a name and a face, what would it look like — and what does it want?",
  "What would you do if you stopped needing anyone's approval?",
  "What is the wildest, most alive version of your future — and why aren't you living it?",
  "What truth are you afraid to admit even to yourself?",
  "What would you lose if you let go of your fear — and what would you gain?",
  "What are you protecting yourself from that is actually protecting you from your greatness?",
  "What step have you been postponing that your gut has already decided on?",
  "What would your life look like if you trusted yourself completely?",
  "What conversation are you avoiding that could change everything?",
  "What would you do if you knew fear was just excitement in disguise?",
  "What is the smallest brave thing you could do today that your future self would thank you for?",
  "What dream did you abandon that deserves to be resurrected?",
  "What would you become if you stopped being afraid of your own power?",

  // ── Aliveness & Identity (30) ────────────────────────────────────────────
  "When do you feel most alive and completely yourself?",
  "What activities make you lose track of time entirely?",
  "Who are you when no one is watching and nothing is expected of you?",
  "What lights you up so much that you would do it even if it exhausted you?",
  "Describe a moment when you felt completely in your element — what were you doing?",
  "What version of yourself emerges when you are truly at peace?",
  "What does joy feel like in your body, and when did you last feel it fully?",
  "What makes you feel like the truest, most unfiltered version of you?",
  "When have you surprised yourself with who you were capable of being?",
  "What do you do that makes time feel like it is bending around you?",
  "What does it feel like when you are being completely honest with yourself?",
  "What environments or atmospheres make you come alive?",
  "What music, place, or experience returns you to yourself?",
  "Who do you become when you are loved well?",
  "What does your most expansive self feel like, and when do you last remember being her?",
  "What part of yourself have you hidden for so long you almost forgot it existed?",
  "What would you reclaim about yourself if you knew it was safe to do so?",
  "What does it feel like when you are in full alignment — mind, body, and soul?",
  "What simple pleasure reminds you of who you really are?",
  "What would you do every single day if obligation had nothing to do with it?",
  "What makes your eyes light up without you even trying?",
  "What kind of person do you feel like when you are at your very best?",
  "When have you felt most free — and what were the conditions that made it possible?",
  "What does your authentic voice sound like when nothing is filtering it?",
  "What would you do with a completely empty day that belonged only to you?",
  "What part of your personality do people rarely get to see — and why?",
  "What have you always known about yourself that you have never fully owned?",
  "What would you call the energy you bring into a room when you are fully yourself?",
  "What does being home in yourself actually feel like?",
  "What would your truest self do today that your conditioned self keeps overriding?",

  // ── Patterns & Signs (30) ────────────────────────────────────────────────
  "What patterns or themes keep recurring in your life, as if the universe is trying to tell you something?",
  "What lessons have followed you across different jobs, relationships, or phases of life?",
  "What do strangers or friends consistently come to you for help with?",
  "What childhood fascinations have never fully left you?",
  "If your struggles were actually preparing you for something, what might that be?",
  "What has life tried to teach you more than once?",
  "What synchronicities or signs have you noticed but been afraid to follow?",
  "What keeps finding its way back to you no matter how far you run from it?",
  "What themes appear in your dreams, daydreams, or moments of stillness?",
  "If your pain had a purpose, what would it be pointing you toward?",
  "What have you had to learn the hard way — and is the lesson complete?",
  "What kind of people are you always drawn to, and what do they reflect about you?",
  "What situation do you keep recreating in different forms?",
  "What story about yourself are you tired of living — and what story wants to replace it?",
  "What keeps showing up in your life as an invitation that you keep declining?",
  "What has your body been signalling to you that your mind refuses to hear?",
  "What does the universe seem to be conspiring to teach you right now?",
  "What have the hardest seasons of your life had in common?",
  "What gift was hidden inside your most painful experience?",
  "What threads connect the most meaningful moments of your life?",
  "What role do you find yourself playing again and again — the healer, the builder, the truth-teller?",
  "What do you keep almost doing — and what stops you each time?",
  "What have you always known but needed life to confirm?",
  "What wound of yours has become a source of unexpected strength?",
  "What story keeps playing in your head that no longer serves the person you are becoming?",
  "What season of life feels like it is finally completing — and what is waiting to begin?",
  "What desire has been consistent since childhood, even if its form has changed?",
  "What has every great loss in your life pointed you toward?",
  "What part of your journey do you now see was not a detour but a direct route?",
  "What clue has the universe been leaving for you that you are only just beginning to read?",

  // ── Legacy & Impact (30) ─────────────────────────────────────────────────
  "What do you want people to feel when they think of the impact you left behind?",
  "How do you want to be remembered by the people whose lives you touched?",
  "What would a child version of you be proud to know you became?",
  "If your eulogy described one thing you stood for, what would that be?",
  "What ripple effect do you hope your existence sends into the future?",
  "What story do you want your grandchildren to tell about you?",
  "What do you hope changes in the world because you were in it?",
  "What would you want written on your legacy, not your tombstone?",
  "Who are the people whose lives will be quietly different because of you?",
  "If you could be remembered for one act of courage, what would it be?",
  "What does leaving the world better than you found it look like for you specifically?",
  "What truth do you want to have lived — not just believed?",
  "What values do you want to have been uncompromising about?",
  "What kind of elder do you want to become?",
  "What would future generations thank you for?",
  "What do you want your presence to have meant to the people closest to you?",
  "If your life were a book, what would its final chapter be about?",
  "What impact do you want to have had on the people who never met you but were touched by your work?",
  "What do you want to have been brave enough to say?",
  "What would it mean to have lived a life without regret — and are you living it?",
  "What do you want to have given more of — and what would you have given less of?",
  "What version of you do you want the next generation to inherit?",
  "What would it mean to you to have truly mattered?",
  "What do you want people to have learned from watching your life?",
  "If you left tomorrow, what would remain — and would it be enough?",
  "What kind of world do you want to have contributed to building?",
  "What would your most meaningful relationships say you gave them?",
  "What do you want to have stood for when standing for it cost something?",
  "What is the most important thing you want to have finished?",
  "If love were your only legacy, how would you have spent your days differently?",

  // ── Relationships & Love (30) ────────────────────────────────────────────
  "What kind of love have you been searching for that you haven't allowed yourself to receive?",
  "What do you most deeply wish others understood about you?",
  "Who brings out the best version of you, and what do they see that you sometimes miss?",
  "What relationship has taught you the most about who you are?",
  "Where in your life are you giving love from a place of fear rather than abundance?",
  "What would you say to someone you love if you knew you had one hour left?",
  "What do you need to forgive — in others or in yourself — to move forward freely?",
  "Who in your life reflects back something you have not yet claimed about yourself?",
  "What does your ideal community of souls look like, and how close are you to building it?",
  "What kind of love do you most want to model for the world?",
  "What do you need from others that you find hardest to ask for?",
  "What kind of friend, partner, or family member do you most want to be?",
  "What would your relationships look like if you showed up without armour?",
  "What has loving someone taught you about loving yourself?",
  "Where are you shrinking yourself to make others comfortable?",
  "What boundary, if you set it, would change everything?",
  "What would you give more of in your relationships if you were less afraid?",
  "What does it feel like to be truly seen — and who has given you that?",
  "What do you wish you had said to someone you have loved and lost?",
  "What pattern in your relationships is it finally time to break?",
  "What do you most want to heal in how you give and receive love?",
  "What does belonging feel like to you, and where do you feel it most?",
  "Who are the people who make you feel like the fullest version of yourself?",
  "What does unconditional love look like in practice — and are you practicing it?",
  "What would change if you let yourself be loved as fully as you love others?",
  "What are you tolerating in a relationship that is quietly costing you yourself?",
  "What does your heart most need to say that it has been waiting to express?",
  "Where in your life are you loving from obligation rather than desire?",
  "What would your relationships feel like if you trusted love completely?",
  "What is the most loving thing you could do for yourself today?",

  // ── Wisdom & Growth (30) ─────────────────────────────────────────────────
  "What is the hardest lesson you have learned that you are now grateful for?",
  "What do you know now that you wish you could whisper to your younger self?",
  "What belief about yourself have you outgrown but not yet released?",
  "What chapter of your life are you most afraid to close — and why?",
  "What wisdom lives in you that the world has not yet asked you to share?",
  "Where in your life are you still playing small when you know you are meant for more?",
  "What truth about yourself have you been dancing around for years?",
  "What would change if you fully trusted your own wisdom?",
  "What have your greatest failures revealed about what you truly value?",
  "What would you do if you stopped waiting for permission?",
  "What have you learned about yourself in the last five years that surprised you?",
  "What old version of yourself is it finally time to thank and release?",
  "What do you know in your bones that you still struggle to act on?",
  "What would the wisest version of your future self tell you right now?",
  "What have you been calling weakness that is actually one of your greatest strengths?",
  "What do you keep learning in new ways because you haven't fully received the lesson yet?",
  "What is the most important thing you have changed your mind about?",
  "What does maturity look like for you — and how close are you to it?",
  "What has grief taught you that joy could not?",
  "What season of struggle ultimately shaped the person you are most proud of becoming?",
  "What would you do differently if you released the need to be right?",
  "What assumption about life has been quietly limiting you?",
  "What have you had to unlearn — and what replaced it?",
  "What does growth feel like in your body when it is actually happening?",
  "What mistake turned out to be a redirection rather than a failure?",
  "What do you understand about yourself now that would have bewildered your younger self?",
  "What wisdom has come to you through stillness that never came through striving?",
  "What part of your story have you been ashamed of that is actually your greatest teacher?",
  "What would you do if you genuinely believed you were enough, exactly as you are?",
  "What is the next level of yourself asking you to step into?",

  // ── Body & Intuition (30) ────────────────────────────────────────────────
  "What does your body know about your purpose that your mind has been ignoring?",
  "When did you last make a decision purely from intuition — and what happened?",
  "What does rest mean to you, and are you allowing yourself enough of it?",
  "What is your body trying to tell you that you keep silencing with busyness?",
  "Where in your body do you feel your calling — and what does it feel like?",
  "What sensations signal to you that you are on the right path?",
  "When have you listened to your gut and had it change everything?",
  "What does your nervous system relax into when you are living in alignment?",
  "What physical experiences make you feel most connected to something greater?",
  "If your body could speak one sentence to your mind right now, what would it say?",
  "What does your body do when you are living in your truth versus living out of alignment?",
  "What physical sensation do you associate with your deepest yes?",
  "What does your body contract around — and what does that contraction know?",
  "Where do you carry your unspoken grief, and what would it need to release?",
  "What does it feel like in your chest when you are about to make the wrong decision?",
  "When have you overridden your body's wisdom — and what did that cost you?",
  "What does your body need more of that your schedule rarely allows?",
  "What does it feel like physically to be in a space where you belong?",
  "What does your breath do when you are living your truth?",
  "What sensation tells you that something is deeply, undeniably right?",
  "What does your body do when it encounters something it recognises as sacred?",
  "What does exhaustion feel like when it comes from misalignment versus meaningful effort?",
  "What would you do differently if you treated your body as a source of wisdom rather than a tool?",
  "What does your body know about love that your mind keeps complicating?",
  "What posture do you hold when you are at your most powerful — and how often do you stand there?",
  "What does your gut say about the most important decision in front of you right now?",
  "What would change if you followed your body's instincts for one full week?",
  "What physical practice returns you to yourself fastest?",
  "What does your body do when it is ready for change before your mind catches up?",
  "What does your body recognise as home?",

  // ── Creativity & Expression (30) ─────────────────────────────────────────
  "What form of expression makes you feel most seen and understood?",
  "What creative impulse have you been suppressing because it felt too indulgent?",
  "If you could communicate one feeling to every person on earth, what would it be and how would you express it?",
  "What would you make if no one ever had to see it?",
  "Where in your life are you editing yourself before you even begin?",
  "What would you create if you knew it was already perfect?",
  "What art, music, or story has cracked you open — and what did it unlock in you?",
  "What medium of expression feels like breathing to you?",
  "If your life were a work of art, what style would it be — and what is it becoming?",
  "What do you long to express that you have never found the words — or courage — for?",
  "What would you make that has never existed before?",
  "What creative act makes you feel closest to whatever you consider divine?",
  "What would you build if beauty were the only measure of success?",
  "What story lives inside you that is waiting for the right moment to be told?",
  "What would your creativity look like if it were completely unchained?",
  "What do you make when you are most at peace — and what does it reveal about you?",
  "What creative gift have you been sitting on because it doesn't feel practical?",
  "What would you write, paint, sing, or build as a love letter to existence?",
  "What does making something with your hands teach you about your soul?",
  "What creative risk have you been circling for years without taking?",
  "What would you express if you knew your audience would understand it completely?",
  "What does the act of creation feel like when it is flowing through you rather than being forced?",
  "What would you make purely for the joy of making it?",
  "What creative vision keeps visiting you that you keep postponing?",
  "What would you create as your offering to the next generation?",
  "What does your creativity want to say that your logic keeps translating into something safer?",
  "What would happen if you gave your creative self three uninterrupted hours every week?",
  "What does your imagination know about your future that your plans haven't caught up with yet?",
  "What would you make if failure and success were equally irrelevant?",
  "What creative act would feel like the truest prayer you have ever offered?",

  // ── Spirituality & Meaning (30) ──────────────────────────────────────────
  "What do you believe you were put on this earth to experience?",
  "When have you felt most connected to something greater than yourself?",
  "What does your soul feel homesick for?",
  "If the universe gave you a sign tomorrow, what would you be hoping it said?",
  "What do you believe about yourself at your most sacred, most honest level?",
  "What mystery about existence do you find yourself returning to again and again?",
  "When do you feel closest to whatever you consider divine or sacred?",
  "What would it mean to live a truly meaningful life — by your own definition?",
  "What spiritual truth have you lived through the body rather than learned from a book?",
  "If your soul chose this life on purpose, what was it here to master?",
  "What does prayer, meditation, or stillness reveal to you that nothing else can?",
  "What do you believe happens when we love someone fully — what does it open?",
  "What sacred question are you living inside of right now?",
  "What does the concept of grace mean to you — and when have you felt it?",
  "What do you believe about the nature of suffering — and has that belief served you?",
  "What would you do differently if you believed your life was a spiritual practice?",
  "What does surrender feel like — and when have you experienced it as a gift rather than a defeat?",
  "What does your soul return to again and again as its source of nourishment?",
  "What do you believe love, at its most expansive, actually is?",
  "What experience has given you the most unshakeable sense that you are not alone?",
  "What does the sacred look like in your ordinary life?",
  "What question has no answer but still feels essential to hold?",
  "What would it mean to trust the timing of your life completely?",
  "What do you believe your soul most needs in this season of your life?",
  "What would change if you treated every person you met as a spiritual teacher?",
  "What does it feel like when you are in harmony with something larger than yourself?",
  "What ancient wisdom tradition or teaching has resonated with something deep in you?",
  "What does wholeness feel like — and how close are you to it?",
  "What does your soul most want to say yes to before this life is complete?",
  "If love is the answer, what is the question your life is asking?",
];

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function getSoulQuestions(): string[] {
  const categorySize = 30;
  const numCategories = 10;
  const picked: string[] = [];

  for (let i = 0; i < numCategories; i++) {
    const slice = ALL_QUESTIONS.slice(i * categorySize, (i + 1) * categorySize);
    const random = Math.floor(Math.random() * slice.length);
    picked.push(slice[random]);
  }

  return shuffle(picked).slice(0, 5);
}
